package semantics

const (
	KeyEvent            = "event"
	KeyDAGRunID         = "dag.run_id"
	KeyDAGTaskID        = "dag.task_id"
	KeyDAGTaskName      = "dag.task_name"
	KeyDAGAttempt       = "dag.attempt"
	KeyDAGNodeID        = "dag.node_id"
	KeyDAGParentNodeID  = "dag.parent_node_id"
	KeyDAGParentNodeIDs = "dag.parent_node_ids"
	KeyMessagingSystem      = "messaging.system"
	KeyMessagingDestination = "messaging.destination"
	KeyMessagingOperation   = "messaging.operation"
	KeyMessagingMessageID   = "messaging.message_id"
	KeySymbol           = "symbol"
	KeyStatus           = "status"
	KeyDurationMS       = "duration_ms"
	KeyRetryCount       = "retry_count"
	KeyQueueWaitMS      = "queue_wait_ms"
	KeyInputSize        = "input_size"
	KeyErrorType        = "error.type"
	KeyErrorMsg         = "error.msg"
	KeyClockUTC         = "clock.utc"
	KeyFromState        = "from_state"
	KeyToState          = "to_state"
	KeyReason           = "reason"
)
