package dailyframe

func DefaultDailyframeSpecs() []Dailyframe {
	return []Dailyframe{
		{
			ID:            1,
			Code:          "PhasePreTokyo",
			StartTimezone: "Asia/Tokyo",
			StartHour:     8,
			StartMinute:   0,
			EndTimezone:   "Asia/Tokyo",
			EndHour:       9,
			EndMinute:     0,
		},
		{
			ID:            2,
			Code:          "PhaseTokyoCore",
			StartTimezone: "Asia/Tokyo",
			StartHour:     9,
			StartMinute:   0,
			EndTimezone:   "Asia/Tokyo",
			EndHour:       15,
			EndMinute:     0,
		},
		{
			ID:            3,
			Code:          "PhaseLateTokyo",
			StartTimezone: "Asia/Tokyo",
			StartHour:     15,
			StartMinute:   0,
			EndTimezone:   "Asia/Tokyo",
			EndHour:       16,
			EndMinute:     0,
		},
		{
			ID:            4,
			Code:          "PhaseLondonEarly",
			StartTimezone: "Europe/London",
			StartHour:     8,
			StartMinute:   0,
			EndTimezone:   "Europe/London",
			EndHour:       11,
			EndMinute:     0,
		},
		{
			ID:            5,
			Code:          "PhaseLondonCore",
			StartTimezone: "Europe/London",
			StartHour:     11,
			StartMinute:   0,
			EndTimezone:   "Europe/London",
			EndHour:       13,
			EndMinute:     0,
		},
		{
			ID:            6,
			Code:          "PhaseLondonLate",
			StartTimezone: "Europe/London",
			StartHour:     13,
			StartMinute:   0,
			EndTimezone:   "Europe/London",
			EndHour:       16,
			EndMinute:     0,
		},
		{
			ID:            7,
			Code:          "PhasePreNewYork",
			StartTimezone: "America/New_York",
			StartHour:     7,
			StartMinute:   0,
			EndTimezone:   "America/New_York",
			EndHour:       8,
			EndMinute:     0,
		},
		{
			ID:            8,
			Code:          "PhaseNewYorkCore",
			StartTimezone: "America/New_York",
			StartHour:     8,
			StartMinute:   0,
			EndTimezone:   "America/New_York",
			EndHour:       11,
			EndMinute:     0,
		},
		{
			ID:            9,
			Code:          "PhaseLateNewYork",
			StartTimezone: "America/New_York",
			StartHour:     11,
			StartMinute:   0,
			EndTimezone:   "America/New_York",
			EndHour:       16,
			EndMinute:     0,
		},
		{
			ID:            10,
			Code:          "PhaseSydneyReset",
			StartTimezone: "Australia/Sydney",
			StartHour:     7,
			StartMinute:   0,
			EndTimezone:   "Australia/Sydney",
			EndHour:       9,
			EndMinute:     0,
		},
	}
}
